pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'hoanglvuitm/vnlawbot'
        DOCKER_CREDENTIALS_ID = 'docker-hub'
        VPS_CREDENTIALS_ID = 'vps_hoanglv'        // ID SSH key trong Jenkins
        VPS_HOST = '31.97.51.25'      // ← sửa địa chỉ VPS
        VPS_USER = 'root'                 // ← sửa user đăng nhập VPS
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: scm.branches,
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'CloneOption', depth: 1, noTags: true, shallow: true]
                    ],
                    userRemoteConfigs: scm.userRemoteConfigs
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend') {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage('Deploy on VPS') {
            steps {
                withCredentials([
                    string(credentialsId: 'langsmith-api-key', variable: 'LANGSMITH_KEY'),
                    string(credentialsId: 'gemini-api-key', variable: 'GEMINI_KEY')
                ]) {
                    sshagent([VPS_CREDENTIALS_ID]) {
                        sh """
                        ssh -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} << 'EOF'
                            docker pull ${DOCKER_IMAGE}:latest
                            docker stop vnlawbot_c || true
                            docker rm vnlawbot_c || true
                            docker run -d \\
                                -p 2824:8000 \\
                                --name vnlawbot_c \\
                                -e LANGSMITH_API_KEY=${LANGSMITH_KEY} \\
                                -e GEMINI_API_KEY=${GEMINI_KEY} \\
                                ${DOCKER_IMAGE}:latest
                        EOF
                        """
                    }
                }
            }
        }
    }
}
